
export const OFFLINE_QUOTES = [
  "Nunca desista, o começo é sempre o mais difícil.",
  "Grandes conquistas começam com pequenas decisões.",
  "Você é mais forte do que imagina.",
  "Acredite no seu potencial.",
  "O sucesso é construído diariamente.",
  "Cada dia é uma nova oportunidade.",
  "Sonhe grande, comece pequeno, mas comece.",
  "Persistência vence talento.",
  "O impossível é apenas uma opinião.",
  "Faça hoje o que outros não fazem.",
  "Coragem é agir mesmo com medo.",
  "Você nasceu para vencer.",
  "Nada muda se você não mudar.",
  "Transforme dor em força.",
  "Seja sua própria motivação.",
  "O esforço de hoje é a vitória de amanhã.",
  "Confie no processo.",
  "A disciplina leva ao sucesso.",
  "Tudo começa com fé.",
  "Continue, mesmo quando for difícil.",
  "Sua determinação define seu destino.",
  "Não espere oportunidade, crie.",
  "Faça acontecer.",
  "Mentalidade forte, resultados fortes.",
  "A vitória começa na mente.",
  "Seja melhor que ontem.",
  "Nunca é tarde para recomeçar.",
  "O foco gera resultados.",
  "Trabalhe em silêncio, deixe o sucesso fazer barulho.",
  "O fracasso ensina o caminho do sucesso.",
  "Você é capaz de coisas incríveis.",
  "Dê o primeiro passo hoje.",
  "Persistir é vencer.",
  "Grandes sonhos exigem grandes atitudes.",
  "Não pare até se orgulhar.",
  "Seja imparável.",
  "A força está dentro de você.",
  "Tudo é possível para quem acredita.",
  "O medo não pode controlar você.",
  "Ação gera transformação.",
  "Cada esforço conta.",
  "Confiança é poder.",
  "Seja luz mesmo na escuridão.",
  "A vitória é para quem insiste.",
  "Supere seus próprios limites.",
  "Seu futuro depende do que você faz hoje.",
  "Transforme sonhos em metas.",
  "Seja constante.",
  "O sucesso é questão de atitude.",
  "Faça valer a pena.",
  "Você pode mais.",
  "Não desista no meio do caminho.",
  "Cresça através dos desafios.",
  "A persistência cria campeões.",
  "Seja exemplo de determinação.",
  "Aprenda com os erros.",
  "Continue avançando.",
  "Seja forte e corajoso.",
  "Nada é impossível para quem tenta.",
  "Faça com paixão.",
  "O progresso é melhor que a perfeição.",
  "Invista em você.",
  "A vitória começa com decisão.",
  "Você é seu único limite.",
  "Nunca pare de lutar.",
  "Seja disciplinado.",
  "Sua jornada é única.",
  "Acredite mais em você.",
  "Supere obstáculos.",
  "O sucesso é consequência do esforço.",
  "Mantenha o foco.",
  "Grandes coisas levam tempo.",
  "Confie no seu talento.",
  "Faça diferente, faça melhor.",
  "O esforço sempre vale a pena.",
  "Desafios constroem força.",
  "Seja resiliente.",
  "A mudança começa em você.",
  "Seja determinado.",
  "Nunca duvide da sua capacidade.",
  "O hoje é o primeiro passo para o amanhã.",
  "Busque evolução constante.",
  "Tenha coragem para continuar.",
  "O sucesso exige sacrifício.",
  "Faça com dedicação.",
  "Seja imparável na busca dos seus sonhos.",
  "A vitória pertence aos persistentes.",
  "Você é protagonista da sua história.",
  "Faça o seu melhor sempre.",
  "A disciplina supera a motivação.",
  "Cada dia é uma nova chance.",
  "Acredite, lute, conquiste.",
  "Seja forte nas dificuldades.",
  "Trabalhe duro em silêncio.",
  "Grandes resultados vêm do esforço contínuo.",
  "A persistência transforma sonhos em realidade.",
  "Nunca pare de tentar.",
  "Você é capaz de vencer qualquer desafio.",
  "O sucesso começa com atitude.",
  "Continue, a vitória está próxima."
];
